version: '3.8'
services:
  postgres:
    image: postgres:16-alpine3.18
    volumes:
      - ./postgres_db_data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    env_file:
      - .env

  redis:
    image: redis:7.2.1-alpine3.18
    ports:
      - 6379:6379